# Generated by Django 5.2.7 on 2026-05-03 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('locked_balance', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='balance_gte_0'), models.CheckConstraint(condition=models.Q(('locked_balance__gte', 0)), name='locked_balance_gte_0')],
                'unique_together': {('user', 'currency')},
            },
        ),
    ]
