# Generated by Django 5.2.7 on 2026-05-03 11:51

from django.db import migrations


def migrate_balances(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Wallet = apps.get_model('users', 'Wallet')
    
    for user in User.objects.all():
        Wallet.objects.create(
            user=user,
            currency='USD',
            balance=user.balance,
            locked_balance=0
        )

def reverse_balances(apps, schema_editor):
    Wallet = apps.get_model('users', 'Wallet')
    Wallet.objects.filter(currency='USD').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_wallet'),
    ]

    operations = [
        migrations.RunPython(migrate_balances, reverse_balances),
    ]
