# Generated by Django 5.2.7 on 2026-05-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_remove_order_asset_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
