# Generated by Django 5.2.7 on 2026-05-03 12:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_transaction_idempotency_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketevent',
            options={'ordering': ['scheduled_at']},
        ),
        migrations.RemoveField(
            model_name='marketevent',
            name='effect_json',
        ),
        migrations.RemoveField(
            model_name='marketevent',
            name='impact',
        ),
        migrations.AddField(
            model_name='asset',
            name='circuit_breaker_tripped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketevent',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketevent',
            name='demand_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='marketevent',
            name='effect_type',
            field=models.CharField(choices=[('demand_spike', 'Demand Spike'), ('demand_crash', 'Demand Crash'), ('supply_shock', 'Supply Shock'), ('volatility_surge', 'Volatility Surge'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='marketevent',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketevent',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 3, 12, 10, 37, 951228, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketevent',
            name='supply_shock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='marketevent',
            name='target_asset',
            field=models.ForeignKey(blank=True, help_text='Null = global event affecting all assets', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='market.asset'),
        ),
        migrations.AddField(
            model_name='marketevent',
            name='volatility_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddIndex(
            model_name='marketevent',
            index=models.Index(fields=['executed', 'expired', 'scheduled_at'], name='market_mark_execute_8c543e_idx'),
        ),
    ]
