# Generated by Django 5.2.7 on 2026-05-03 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_marketevent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='market.asset')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['asset', 'timestamp'], name='market_pric_asset_i_220c7d_idx')],
            },
        ),
    ]
